name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Fix
            git reset --hard
            git pull origin main
            docker build -t react-app .
            docker stop react-container || true
            docker rm react-container || true
            docker run -d -p 3004:80 --restart always --name react-container react-app
